In [1]:
import pandas as pd
import matplotlib as pyplot

In [2]:
# Importing the csv file into pandas
df = pd.read_csv('coffee_shop_data.csv')
df

,OrderID,Date,Region,Store,Category,Product,UnitsSold,Revenue,Cost,DiscountPercent
0,1001,2026-05-01,East,Providence Cafe,Coffee,Latte,45,247.5,135.0,0
1,1002,2026-05-01,East,Providence Cafe,Food,Muffin,30,105.0,42.0,10
2,1003,2026-05-01,West,Seattle Central,Coffee,Cold Brew,52,286.0,140.0,5
3,1004,2026-05-02,South,Austin Beans,Tea,Chai Latte,28,126.0,56.0,0
4,1005,2026-05-02,West,Seattle Central,Food,Bagel,40,140.0,52.0,15
5,1006,2026-05-02,East,Providence Cafe,Coffee,Cappuccino,38,209.0,114.0,0
6,1007,2026-05-03,South,Austin Beans,Coffee,Americano,60,210.0,78.0,0
7,1008,2026-05-03,West,Seattle Central,Tea,Green Tea,25,87.5,30.0,0
8,1009,2026-05-03,East,Providence Cafe,Food,Croissant,18,81.0,36.0,20
9,1010,2026-05-04,South,Austin Beans,Food,Cookie,50,125.0,40.0,0
10,1011,2026-05-04,West,Seattle Central,Coffee,Mocha,33,198.0,102.0,10
11,1012,2026-05-04,East,Providence Cafe,Tea,Matcha Latte,20,110.0,48.0,5
12,1013,2026-05-05,South,Austin Beans,Coffee,Espresso,70,210.0,84.0,0
13,1014,2026-05-05,West,Seattle Central,Food,Scone,22,88.0,35.0,0
14,1015,2026-05-05,East,Providence Cafe,Coffee,Flat White,27,162.0,81.0,0

In [4]:
df.shape
rows,cols = df.shape
print("Rows:",rows)
print("Columns:",cols)

Rows: 15
Columns: 10

In [5]:
df.describe()

           OrderID  UnitsSold     Revenue        Cost  DiscountPercent
count    15.000000  15.000000   15.000000   15.000000        15.000000
mean   1008.000000  37.200000  159.000000   71.533333         4.333333
std       4.472136  15.469786   64.005301   36.935981         6.510065
min    1001.000000  18.000000   81.000000   30.000000         0.000000
25%    1004.500000  26.000000  107.500000   41.000000         0.000000
50%    1008.000000  33.000000  140.000000   56.000000         0.000000
75%    1011.500000  47.500000  209.500000   93.000000         7.500000
max    1015.000000  70.000000  286.000000  140.000000        20.000000

In [6]:
df.columns

Index(['OrderID', 'Date', 'Region', 'Store', 'Category', 'Product',
       'UnitsSold', 'Revenue', 'Cost', 'DiscountPercent'],
      dtype='object')

In [7]:
df.dtypes

OrderID              int64
Date                object
Region              object
Store               object
Category            object
Product             object
UnitsSold            int64
Revenue            float64
Cost               float64
DiscountPercent      int64
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          15 non-null     int64
 1   Date             15 non-null     object
 2   Region           15 non-null     object
 3   Store            15 non-null     object
 4   Category         15 non-null     object
 5   Product          15 non-null     object
 6   UnitsSold        15 non-null     int64
 7   Revenue          15 non-null     float64
 8   Cost             15 non-null     float64
 9   DiscountPercent  15 non-null     int64
dtypes: float64(2), int64(3), object(5)
memory usage: 1.3+ KB

In [9]:
df.head(5)

,OrderID,Date,Region,Store,Category,Product,UnitsSold,Revenue,Cost,DiscountPercent
0,1001,2026-05-01,East,Providence Cafe,Coffee,Latte,45,247.5,135.0,0
1,1002,2026-05-01,East,Providence Cafe,Food,Muffin,30,105.0,42.0,10
2,1003,2026-05-01,West,Seattle Central,Coffee,Cold Brew,52,286.0,140.0,5
3,1004,2026-05-02,South,Austin Beans,Tea,Chai Latte,28,126.0,56.0,0
4,1005,2026-05-02,West,Seattle Central,Food,Bagel,40,140.0,52.0,15

In [20]:
df.isnull().sum()

OrderID            0
Date               0
Region             0
Store              0
Category           0
Product            0
UnitsSold          0
Revenue            0
Cost               0
DiscountPercent    0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Which store performs the best
df.groupby('Store')['Revenue'].sum().sort_values(ascending=False)

Store
Providence Cafe    914.5
Seattle Central    799.5
Austin Beans       671.0
Name: Revenue, dtype: float64

In [16]:
# Which product categories are the most profitable
df.groupby('Category')['Revenue'].sum().sort_values(ascending=False)

Category
Coffee    1522.5
Food       539.0
Tea        323.5
Name: Revenue, dtype: float64

In [ ]:
# Whether discounts are negatively affecting profits